export const langOptions = [
    { 'code':'af', 'name': 'Afrikaans'},
    { 'code':'ar', 'name': 'Arabic'},
    { 'code':'ast', 'name': 'Asturian'},
    { 'code':'az', 'name': 'Azerbaijani'},
    { 'code':'bg', 'name': 'Bulgarian'},
    { 'code':'be', 'name': 'Belarusian'},
    { 'code':'bn', 'name': 'Bengali'},
    { 'code':'br', 'name': 'Breton'},
    { 'code':'bs', 'name': 'Bosnian'},
    { 'code':'ca', 'name': 'Catalan'},
    { 'code':'cs', 'name': 'Czech'},
    { 'code':'cy', 'name': 'Welsh'},
    { 'code':'da', 'name': 'Danish'},
    { 'code':'de', 'name': 'German'},
    { 'code':'dsb', 'name': 'Lower Sorbian'},
    { 'code':'el', 'name': 'Greek'},
    { 'code':'en', 'name': 'English'},
    { 'code':'en-au', 'name': 'Australian English'},
    { 'code':'en-gb', 'name': 'British English'},
    { 'code':'eo', 'name': 'Esperanto'},
    { 'code':'es', 'name': 'Spanish'},
    { 'code':'es-ar', 'name': 'Argentinian Spanish'},
    { 'code':'es-co', 'name': 'Colombian Spanish'},
    { 'code':'es-mx', 'name': 'Mexican Spanish'},
    { 'code':'es-ni', 'name': 'Nicaraguan Spanish'},
    { 'code':'es-ve', 'name': 'Venezuelan Spanish'},
    { 'code':'et', 'name': 'Estonian'},
    { 'code':'eu', 'name': 'Basque'},
    { 'code':'fa', 'name': 'Persian'},
    { 'code':'fi', 'name': 'Finnish'},
    { 'code':'fr', 'name': 'French'},
    { 'code':'fy', 'name': 'Frisian'},
    { 'code':'ga', 'name': 'Irish'},
    { 'code':'gd', 'name': 'Scottish Gaelic'},
    { 'code':'gl', 'name': 'Galician'},
    { 'code':'he', 'name': 'Hebrew'},
    { 'code':'hi', 'name': 'Hindi'},
    { 'code':'hr', 'name': 'Croatian'},
    { 'code':'hsb', 'name': 'Upper Sorbian'},
    { 'code':'hu', 'name': 'Hungarian'},
    { 'code':'ia', 'name': 'Interlingua'},
    { 'code':'id', 'name': 'Indonesian'},
    { 'code':'io', 'name': 'Ido'},
    { 'code':'is', 'name': 'Icelandic'},
    { 'code':'it', 'name': 'Italian'},
    { 'code':'ja', 'name': 'Japanese'},
    { 'code':'ka', 'name': 'Georgian'},
    { 'code':'kk', 'name': 'Kazakh'},
    { 'code':'km', 'name': 'Khmer'},
    { 'code':'kn', 'name': 'Kannada'},
    { 'code':'ko', 'name': 'Korean'},
    { 'code':'lb', 'name': 'Luxembourgish'},
    { 'code':'lt', 'name': 'Lithuanian'},
    { 'code':'lv', 'name': 'Latvian'},
    { 'code':'mk', 'name': 'Macedonian'},
    { 'code':'ml', 'name': 'Malayalam'},
    { 'code':'mn', 'name': 'Mongolian'},
    { 'code':'mr', 'name': 'Marathi'},
    { 'code':'my', 'name': 'Burmese'},
    { 'code':'nb', 'name': 'Norwegian Bokmål'},
    { 'code':'ne', 'name': 'Nepali'},
    { 'code':'nl', 'name': 'Dutch'},
    { 'code':'nn', 'name': 'Norwegian Nynorsk'},
    { 'code':'os', 'name': 'Ossetic'},
    { 'code':'pa', 'name': 'Punjabi'},
    { 'code':'pl', 'name': 'Polish'},
    { 'code':'pt', 'name': 'Portuguese'},
    { 'code':'pt-br', 'name': 'Brazilian Portuguese'},
    { 'code':'ro', 'name': 'Romanian'},
    { 'code':'ru', 'name': 'Russian'},
    { 'code':'sk', 'name': 'Slovak'},
    { 'code':'sl', 'name': 'Slovenian'},
    { 'code':'sq', 'name': 'Albanian'},
    { 'code':'sr', 'name': 'Serbian'},
    { 'code':'sr-latn', 'name': 'Serbian Latin'},
    { 'code':'sv', 'name': 'Swedish'},
    { 'code':'sw', 'name': 'Swahili'},
    { 'code':'ta', 'name': 'Tamil'},
    { 'code':'te', 'name': 'Telugu'},
    { 'code':'th', 'name': 'Thai'},
    { 'code':'tr', 'name': 'Turkish'},
    { 'code':'tt', 'name': 'Tatar'},
    { 'code':'udm', 'name': 'Udmurt'},
    { 'code':'uk', 'name': 'Ukrainian'},
    { 'code':'ur', 'name': 'Urdu'},
    { 'code':'vi', 'name': 'Vietnamese'},
    { 'code':'zh-hans', 'name': 'Simplified Chinese'},
    { 'code':'zh-hant', 'name': 'Traditional Chinese'}
]

export const langMap = {
    'af': 'Afrikaans',
    'ar': 'Arabic',
    'ast': 'Asturian',
    'az': 'Azerbaijani',
    'bg': 'Bulgarian',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'br': 'Breton',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'cs': 'Czech',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'dsb': 'Lower Sorbian',
    'el': 'Greek',
    'en': 'English',
    'en-au': 'Australian English',
    'en-gb': 'British English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'es-ar': 'Argentinian Spanish',
    'es-co': 'Colombian Spanish',
    'es-mx': 'Mexican Spanish',
    'es-ni': 'Nicaraguan Spanish',
    'es-ve': 'Venezuelan Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fr': 'French',
    'fy': 'Frisian',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'gl': 'Galician',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hr': 'Croatian',
    'hsb': 'Upper Sorbian',
    'hu': 'Hungarian',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'ja': 'Japanese',
    'ka': 'Georgian',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'lb': 'Luxembourgish',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'my': 'Burmese',
    'nb': 'Norwegian Bokmål',
    'ne': 'Nepali',
    'nl': 'Dutch',
    'nn': 'Norwegian Nynorsk',
    'os': 'Ossetic',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'pt-br': 'Brazilian Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'sr-latn': 'Serbian Latin',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'tt': 'Tatar',
    'udm': 'Udmurt',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'vi': 'Vietnamese',
    'zh-hans': 'Simplified Chinese',
    'zh-hant': 'Traditional Chinese'
}



