export const FETCH_TOKEN = "FETCH_TOKEN";
export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const FETCH_TOKEN_SUCCESSFUL = "FETCH_TOKEN_SUCCESSFUL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_REJECTED = "FETCH_NOTES_REJECTED";
export const FETCH_NOTES_FULFILLED = "FETCH_NOTES_FULFILLED";

export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const SET_UPDATE_NOTE = "SET_UPDATE_NOTE";
export const UPDATE_NOTE= "UPDATE_NOTE";
export const CANCEL_UPDATE = "CANCEL_UPDATE";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE = "DELETE_NOTE";

export const SEARCH_NOTES = "SEARCH_NOTES";

export const SUCCESSFUL_ACTION = "SUCCESSFUL_ACTION";
export const REJECTED_ACTION = "REJECTED_ACTION";
export const INFO_ACTION = "INFO_ACTION"; 

export const WARNING = "WARNING";
export const SUCCESS = "SUCCESS";